name: Yuriy Liskov
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  # - jekyll-multiple-languages-plugin
languages: ["en", "ru"]
exclude:
  - site_*.bat
  - bak_*
  - notes.txt
  - "*.bak*"
  - "*.tmp*"
  - "*.1"
exclude_from_localization:
  - _posts
