# Begin SEO tags
title: Yurii Lyskov's Personal Site
description: Some funny stuff about me
url: https://yuliskov.github.io
author: Yurii Lyskov
logo: /img/my_photo2.png
# End SEO tags
name: Yurii Liskov
email: yuliskov@gmail.com
email_obf: moc.liamg@voksiluy
phone: +38 (066) 354 68 22
phone_obf: 22 86 453 (660) 83+
root_url: https://yuliskov.github.io
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
    - jekyll-multiple-languages-plugin
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-email-protect
languages: ["en", "ru"]
exclude:
    - site_*.bat
    - bak_*
    - notes.txt
    - "*.bak*"
    - "*.tmp*"
    - "*.gen"
exclude_from_localizations:
    - _posts
sass:
    style: compressed
